import React, { useState } from 'react';
import { Share2, MessageSquare, Star, CheckCircle, X, Printer } from 'lucide-react';
import { toast } from 'react-toastify';
import { useLanguage } from '../../context/LanguageContext';
import { printOfficialReport } from '../../utils/reportPrinter';

const ActionToolbar = ({ title = 'Report', summary = 'AgriSathi Analysis Report', printableId = null, onPrint }) => {
  const { language } = useLanguage();
  const [showFeedbackModal, setShowFeedbackModal] = useState(false);
  const [rating, setRating] = useState(5);
  const [feedbackText, setFeedbackText] = useState('');
  const [submitted, setSubmitted] = useState(false);

  const handlePrintDownload = () => {
    if (onPrint) {
      onPrint();
      return;
    }

    // Extract printable container content or use page body
    let printHtml = '';
    const container = printableId ? document.getElementById(printableId) : document.querySelector('main');
    if (container) {
      printHtml = container.innerHTML;
    } else {
      printHtml = document.body.innerHTML;
    }

    printOfficialReport({
      title: `AgriSathi Official Diagnostic & Advisory Report: ${title}`,
      subtitle: summary,
      farmerName: 'Subhadip Ghosh',
      location: 'Barasat, North 24 Parganas, West Bengal',
      htmlContent: printHtml
    });
  };

  const handleShare = async () => {
    const shareData = {
      title: `AgriSathi: ${title}`,
      text: `${summary} - Generated by AgriSathi AI Platform`,
      url: window.location.href,
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
        toast.success(language === 'bn' ? 'রিপোর্টটি শেয়ার করা হয়েছে!' : language === 'hi' ? 'रिपोर्ट साझा की गई!' : 'Report shared successfully!');
      } catch (_) {}
    } else {
      try {
        await navigator.clipboard.writeText(window.location.href);
        toast.success(language === 'bn' ? 'লিঙ্ক ক্লিপবোর্ডে কপি করা হয়েছে!' : language === 'hi' ? 'लिंक क्लिपबोर्ड में कॉपी किया गया!' : 'Report link copied to clipboard!');
      } catch (_) {
        toast.info('Share URL: ' + window.location.href);
      }
    }
  };

  const handleSubmitFeedback = (e) => {
    e.preventDefault();
    setSubmitted(true);
    toast.success(language === 'bn' ? 'আপনার মতামতের জন্য ধন্যবাদ!' : language === 'hi' ? 'आपकी प्रतिक्रिया के लिए धन्यवाद!' : 'Thank you for your valuable feedback!');
    setTimeout(() => {
      setShowFeedbackModal(false);
      setSubmitted(false);
      setFeedbackText('');
    }, 1200);
  };

  return (
    <>
      <div className="flex flex-wrap items-center gap-3 bg-gradient-to-r from-gray-50 to-green-50 p-4 rounded-xl border border-gray-200 mt-6 shadow-xs no-print">
        <button
          type="button"
          onClick={handlePrintDownload}
          className="flex-1 min-w-[140px] flex items-center justify-center gap-2 bg-green-600 hover:bg-green-700 text-white py-2.5 px-4 rounded-xl font-bold text-xs shadow-md transition transform active:scale-95"
        >
          <Printer className="w-4 h-4" />
          {language === 'bn' ? 'প্রিন্ট / ডাউনলোড সম্পূর্ণ PDF রিপোর্ট' : language === 'hi' ? 'प्रिंट / डाउनलोड पूर्ण PDF रिपोर्ट' : 'Print / Download Full PDF Report'}
        </button>

        <button
          type="button"
          onClick={handleShare}
          className="flex-1 min-w-[120px] flex items-center justify-center gap-2 bg-blue-600 hover:bg-blue-700 text-white py-2.5 px-4 rounded-xl font-bold text-xs shadow-md transition transform active:scale-95"
        >
          <Share2 className="w-4 h-4" />
          {language === 'bn' ? 'শেয়ার করুন' : language === 'hi' ? 'शेयर करें' : 'Share Report'}
        </button>

        <button
          type="button"
          onClick={() => setShowFeedbackModal(true)}
          className="flex-1 min-w-[120px] flex items-center justify-center gap-2 bg-amber-500 hover:bg-amber-600 text-white py-2.5 px-4 rounded-xl font-bold text-xs shadow-md transition transform active:scale-95"
        >
          <MessageSquare className="w-4 h-4" />
          {language === 'bn' ? 'মতামত দিন' : language === 'hi' ? 'प्रतिक्रिया दें' : 'Give Feedback'}
        </button>
      </div>

      {/* Feedback Modal */}
      {showFeedbackModal && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-xs z-[99999] flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl max-w-md w-full p-6 shadow-2xl relative animate-scaleUp">
            <button
              onClick={() => setShowFeedbackModal(false)}
              className="absolute top-4 right-4 text-gray-400 hover:text-gray-600 p-1"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="text-center mb-4">
              <div className="w-12 h-12 bg-amber-100 text-amber-600 rounded-full flex items-center justify-center mx-auto mb-2">
                <MessageSquare className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold text-gray-800">
                {language === 'bn' ? 'মতামত প্রদান করুন' : language === 'hi' ? 'अपनी प्रतिक्रिया दें' : 'Rate & Provide Feedback'}
              </h3>
              <p className="text-xs text-gray-500 mt-1">
                {language === 'bn' ? 'আপনার মতামত আমাদের পরিষেবা আরও উন্নত করতে সাহায্য করে।' : language === 'hi' ? 'आपकी प्रतिक्रिया हमारी सेवा को बेहतर बनाने में मदद करती है।' : 'Your feedback helps us improve AgriSathi recommendations.'}
              </p>
            </div>

            {submitted ? (
              <div className="text-center py-6 text-emerald-600">
                <CheckCircle className="w-12 h-12 mx-auto mb-2 animate-bounce" />
                <p className="font-bold text-sm">
                  {language === 'bn' ? 'মতামত সফলভাবে জমা দেওয়া হয়েছে!' : language === 'hi' ? 'प्रतिक्रिया सफलतापूर्वक भेजी गई!' : 'Feedback Submitted Successfully!'}
                </p>
              </div>
            ) : (
              <form onSubmit={handleSubmitFeedback} className="space-y-4">
                <div className="flex justify-center gap-2 my-2">
                  {[1, 2, 3, 4, 5].map((star) => (
                    <button
                      key={star}
                      type="button"
                      onClick={() => setRating(star)}
                      className="p-1 focus:outline-none transform transition hover:scale-110"
                    >
                      <Star className={`w-8 h-8 ${star <= rating ? 'text-amber-400 fill-amber-400' : 'text-gray-300'}`} />
                    </button>
                  ))}
                </div>

                <textarea
                  rows="3"
                  value={feedbackText}
                  onChange={(e) => setFeedbackText(e.target.value)}
                  placeholder={
                    language === 'bn'
                      ? 'আপনার মতামত লিখুন (ঐচ্ছিক)...'
                      : language === 'hi'
                      ? 'अपनी टिप्पणी लिखें (वैकल्पिक)...'
                      : 'Write your feedback or suggestion...'
                  }
                  className="w-full p-3 border rounded-xl text-xs focus:ring-2 focus:ring-amber-400 focus:outline-none"
                />

                <button
                  type="submit"
                  className="w-full py-3 bg-amber-500 hover:bg-amber-600 text-white font-bold text-sm rounded-xl shadow-lg transition"
                >
                  {language === 'bn' ? 'জমা দিন' : language === 'hi' ? 'जमा करें' : 'Submit Feedback'}
                </button>
              </form>
            )}
          </div>
        </div>
      )}
    </>
  );
};

export default ActionToolbar;
